// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cashfree-go/pkg/models/shared"
	"github.com/speakeasy-sdks/cashfree-go/pkg/utils"
	"net/http"
)

type GetPGReconciliationRequest struct {
	// application/json
	AcceptMedia *string `header:"style=simple,explode=false,name=Accept-Media"`
	// Request body to fetch detailed list of transactions
	FetchPGReconRequest *shared.FetchPGReconRequest `request:"mediaType=application/json"`
	// API version to be used. Format is in YYYY-MM-DD
	XAPIVersion string `default:"2022-09-01" header:"style=simple,explode=false,name=x-api-version"`
	// Idempotency works by saving the resulting status code and body of the first request made for any given idempotency key, regardless of whether it succeeded or failed. Subsequent requests with the same key return the same result, including 500 errors.
	//
	// Currently supported on all POST calls that uses x-client-id & x-client-secret. To use enable, pass x-idempotency-key in the request header. The value of this header must be unique to each operation you are trying to do. One example can be to use the same order_id that you pass while creating orders
	//
	XIdempotencyKey *string `header:"style=simple,explode=false,name=x-idempotency-key"`
	// Request id for the API call. Can be used to resolve tech issues. Communicate this in your tech related queries to cashfree
	XRequestID *string `header:"style=simple,explode=false,name=x-request-id"`
}

func (g GetPGReconciliationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPGReconciliationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetPGReconciliationRequest) GetAcceptMedia() *string {
	if o == nil {
		return nil
	}
	return o.AcceptMedia
}

func (o *GetPGReconciliationRequest) GetFetchPGReconRequest() *shared.FetchPGReconRequest {
	if o == nil {
		return nil
	}
	return o.FetchPGReconRequest
}

func (o *GetPGReconciliationRequest) GetXAPIVersion() string {
	if o == nil {
		return ""
	}
	return o.XAPIVersion
}

func (o *GetPGReconciliationRequest) GetXIdempotencyKey() *string {
	if o == nil {
		return nil
	}
	return o.XIdempotencyKey
}

func (o *GetPGReconciliationRequest) GetXRequestID() *string {
	if o == nil {
		return nil
	}
	return o.XRequestID
}

type GetPGReconciliationResponse struct {
	ContentType string
	// OK
	FetchPGRecon *shared.FetchPGRecon
	Headers      map[string][]string
	StatusCode   int
	RawResponse  *http.Response
}

func (o *GetPGReconciliationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPGReconciliationResponse) GetFetchPGRecon() *shared.FetchPGRecon {
	if o == nil {
		return nil
	}
	return o.FetchPGRecon
}

func (o *GetPGReconciliationResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *GetPGReconciliationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPGReconciliationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
