// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cashfree-go/pkg/models/shared"
	"net/http"
)

type GetPaymentLinkOrdersRequest struct {
	// The payment link ID for which you want to view the order details.
	LinkID string `pathParam:"style=simple,explode=false,name=link_id"`
	// API version to be used. Format is in YYYY-MM-DD
	XAPIVersion string `header:"style=simple,explode=false,name=x-api-version"`
	// Request id for the API call. Can be used to resolve tech issues. Communicate this in your tech related queries to cashfree
	XRequestID *string `header:"style=simple,explode=false,name=x-request-id"`
}

func (o *GetPaymentLinkOrdersRequest) GetLinkID() string {
	if o == nil {
		return ""
	}
	return o.LinkID
}

func (o *GetPaymentLinkOrdersRequest) GetXAPIVersion() string {
	if o == nil {
		return ""
	}
	return o.XAPIVersion
}

func (o *GetPaymentLinkOrdersRequest) GetXRequestID() *string {
	if o == nil {
		return nil
	}
	return o.XRequestID
}

type GetPaymentLinkOrdersResponse struct {
	ContentType string
	Headers     map[string][]string
	// OK
	LinkOrdersResponses []shared.LinkOrdersResponse
	StatusCode          int
	RawResponse         *http.Response
}

func (o *GetPaymentLinkOrdersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPaymentLinkOrdersResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *GetPaymentLinkOrdersResponse) GetLinkOrdersResponses() []shared.LinkOrdersResponse {
	if o == nil {
		return nil
	}
	return o.LinkOrdersResponses
}

func (o *GetPaymentLinkOrdersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPaymentLinkOrdersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
