// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cashfree-go/pkg/models/shared"
	"net/http"
)

type SubmitOTPRequestRequest struct {
	// Request body to submit/resend headless OTP. To use this API make sure you have headless OTP enabled for your account
	OTPRequest *shared.OTPRequest `request:"mediaType=application/json"`
	// The order or invoice ID for which you want to view the payment details.
	PaymentID string `pathParam:"style=simple,explode=false,name=payment_id"`
	// API version to be used. Format is in YYYY-MM-DD
	XAPIVersion string `header:"style=simple,explode=false,name=x-api-version"`
	// Request id for the API call. Can be used to resolve tech issues. Communicate this in your tech related queries to cashfree
	XRequestID *string `header:"style=simple,explode=false,name=x-request-id"`
}

func (o *SubmitOTPRequestRequest) GetOTPRequest() *shared.OTPRequest {
	if o == nil {
		return nil
	}
	return o.OTPRequest
}

func (o *SubmitOTPRequestRequest) GetPaymentID() string {
	if o == nil {
		return ""
	}
	return o.PaymentID
}

func (o *SubmitOTPRequestRequest) GetXAPIVersion() string {
	if o == nil {
		return ""
	}
	return o.XAPIVersion
}

func (o *SubmitOTPRequestRequest) GetXRequestID() *string {
	if o == nil {
		return nil
	}
	return o.XRequestID
}

type SubmitOTPRequestResponse struct {
	ContentType string
	Headers     map[string][]string
	// OK
	OTPResponseEntity *shared.OTPResponseEntity
	StatusCode        int
	RawResponse       *http.Response
}

func (o *SubmitOTPRequestResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SubmitOTPRequestResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *SubmitOTPRequestResponse) GetOTPResponseEntity() *shared.OTPResponseEntity {
	if o == nil {
		return nil
	}
	return o.OTPResponseEntity
}

func (o *SubmitOTPRequestResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SubmitOTPRequestResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
