// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasAPIError502Type - api_error
type SchemasAPIError502Type string

const (
	SchemasAPIError502TypeAPIError SchemasAPIError502Type = "api_error"
)

func (e SchemasAPIError502Type) ToPointer() *SchemasAPIError502Type {
	return &e
}

func (e *SchemasAPIError502Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_error":
		*e = SchemasAPIError502Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasAPIError502Type: %v", v)
	}
}

// APIError502 - Bank related Error
type APIError502 struct {
	// `bank_processing_failure` will be returned here to denote failure at bank.
	//
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// api_error
	Type *SchemasAPIError502Type `json:"type,omitempty"`
}

var _ error = &APIError502{}

func (e *APIError502) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
