// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/cashfree-go/pkg/types"
)

type APIError409 struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// invalid_request_error
	Type *string `const:"invalid_request_error" json:"type,omitempty"`
}

var _ error = &APIError409{}

func (e *APIError409) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
