// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasAPIErrorType - api_error
type SchemasAPIErrorType string

const (
	SchemasAPIErrorTypeAPIError SchemasAPIErrorType = "api_error"
)

func (e SchemasAPIErrorType) ToPointer() *SchemasAPIErrorType {
	return &e
}

func (e *SchemasAPIErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_error":
		*e = SchemasAPIErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasAPIErrorType: %v", v)
	}
}

// APIError - Error at cashfree's server
type APIError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// api_error
	Type *SchemasAPIErrorType `json:"type,omitempty"`
}

var _ error = &APIError{}

func (e *APIError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
