// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/cashfree-go/pkg/models/shared"
)

// APIError404 - Error when resource requested is not found
type APIError404 struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// invalid_request_error
	Type *shared.APIError404Type `json:"type,omitempty"`
}

var _ error = &APIError404{}

func (e *APIError404) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
