// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/cashfree-go/pkg/models/shared"
)

// APIError - Error at cashfree's server
type APIError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// api_error
	Type *shared.APIErrorType `json:"type,omitempty"`
}

var _ error = &APIError{}

func (e *APIError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
