// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// Type - invalid_request_error
type Type string

const (
	TypeInvalidRequestError Type = "invalid_request_error"
)

func (e Type) ToPointer() *Type {
	return &e
}

func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invalid_request_error":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

// APIError404 - Error when resource requested is not found
type APIError404 struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// invalid_request_error
	Type *Type `json:"type,omitempty"`
}

var _ error = &APIError404{}

func (e *APIError404) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
