// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// APIError409Type - invalid_request_error
type APIError409Type string

const (
	APIError409TypeInvalidRequestError APIError409Type = "invalid_request_error"
)

func (e APIError409Type) ToPointer() *APIError409Type {
	return &e
}

func (e *APIError409Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invalid_request_error":
		*e = APIError409Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for APIError409Type: %v", v)
	}
}

type APIError409 struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// invalid_request_error
	Type *APIError409Type `json:"type,omitempty"`
}

var _ error = &APIError409{}

func (e *APIError409) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
