// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/cashfree-go/pkg/types"
)

type APIError502 struct {
	// `bank_processing_failure` will be returned here to denote failure at bank.
	//
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// api_error
	Type *string `const:"api_error" json:"type,omitempty"`
}

var _ error = &APIError502{}

func (e *APIError502) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
