// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/cashfree-go/pkg/types"
)

type BadRequestError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Type    *string `const:"invalid_request_error" json:"type,omitempty"`
}

var _ error = &BadRequestError{}

func (e *BadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
