// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/cashfree-go/pkg/models/shared"
)

type IdempotencyError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// idempotency_error
	Type *shared.IdempotencyErrorType `json:"type,omitempty"`
}

var _ error = &IdempotencyError{}

func (e *IdempotencyError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
