// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasIdempotencyErrorType - idempotency_error
type SchemasIdempotencyErrorType string

const (
	SchemasIdempotencyErrorTypeIdempotencyError SchemasIdempotencyErrorType = "idempotency_error"
)

func (e SchemasIdempotencyErrorType) ToPointer() *SchemasIdempotencyErrorType {
	return &e
}

func (e *SchemasIdempotencyErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "idempotency_error":
		*e = SchemasIdempotencyErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasIdempotencyErrorType: %v", v)
	}
}

type IdempotencyError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// idempotency_error
	Type *SchemasIdempotencyErrorType `json:"type,omitempty"`
}

var _ error = &IdempotencyError{}

func (e *IdempotencyError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
