// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// APIError502Type - api_error
type APIError502Type string

const (
	APIError502TypeAPIError APIError502Type = "api_error"
)

func (e APIError502Type) ToPointer() *APIError502Type {
	return &e
}

func (e *APIError502Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_error":
		*e = APIError502Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for APIError502Type: %v", v)
	}
}
