// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// IdempotencyErrorType - idempotency_error
type IdempotencyErrorType string

const (
	IdempotencyErrorTypeIdempotencyError IdempotencyErrorType = "idempotency_error"
)

func (e IdempotencyErrorType) ToPointer() *IdempotencyErrorType {
	return &e
}

func (e *IdempotencyErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "idempotency_error":
		*e = IdempotencyErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IdempotencyErrorType: %v", v)
	}
}
