// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WalletOffer struct {
	Provider *string `json:"provider,omitempty"`
}

func (o *WalletOffer) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

type OfferWallet struct {
	App *WalletOffer `json:"app,omitempty"`
}

func (o *OfferWallet) GetApp() *WalletOffer {
	if o == nil {
		return nil
	}
	return o.App
}
