// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CardOffer struct {
	// Bank Name of Card.
	BankName   string   `json:"bank_name"`
	SchemeName []string `json:"scheme_name"`
	Type       []string `json:"type"`
}

func (o *CardOffer) GetBankName() string {
	if o == nil {
		return ""
	}
	return o.BankName
}

func (o *CardOffer) GetSchemeName() []string {
	if o == nil {
		return []string{}
	}
	return o.SchemeName
}

func (o *CardOffer) GetType() []string {
	if o == nil {
		return []string{}
	}
	return o.Type
}

type OfferCard struct {
	Card CardOffer `json:"card"`
}

func (o *OfferCard) GetCard() CardOffer {
	if o == nil {
		return CardOffer{}
	}
	return o.Card
}
