// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferNBNetbanking struct {
	BankName *string `json:"bank_name,omitempty"`
}

func (o *OfferNBNetbanking) GetBankName() *string {
	if o == nil {
		return nil
	}
	return o.BankName
}

type OfferNB struct {
	Netbanking OfferNBNetbanking `json:"netbanking"`
}

func (o *OfferNB) GetNetbanking() OfferNBNetbanking {
	if o == nil {
		return OfferNBNetbanking{}
	}
	return o.Netbanking
}
