// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferPaylaterPaylaterOffer struct {
	Provider *string `json:"provider,omitempty"`
}

func (o *OfferPaylaterPaylaterOffer) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

type OfferPaylater struct {
	Paylater OfferPaylaterPaylaterOffer `json:"paylater"`
}

func (o *OfferPaylater) GetPaylater() OfferPaylaterPaylaterOffer {
	if o == nil {
		return OfferPaylaterPaylaterOffer{}
	}
	return o.Paylater
}
