// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferAll struct {
	// All offers applicable
	All AllOffers `json:"all"`
}

func (o *OfferAll) GetAll() AllOffers {
	if o == nil {
		return AllOffers{}
	}
	return o.All
}
