// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferEMIEMIOffer struct {
	// Bank Name
	Issuer  string  `json:"issuer"`
	Tenures []int64 `json:"tenures"`
	// Type of emi offer. Possible values are `credit_card_emi`, `debit_card_emi`, `cardless_emi`
	Type string `json:"type"`
}

func (o *OfferEMIEMIOffer) GetIssuer() string {
	if o == nil {
		return ""
	}
	return o.Issuer
}

func (o *OfferEMIEMIOffer) GetTenures() []int64 {
	if o == nil {
		return []int64{}
	}
	return o.Tenures
}

func (o *OfferEMIEMIOffer) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

type OfferEMI struct {
	Emi OfferEMIEMIOffer `json:"emi"`
}

func (o *OfferEMI) GetEmi() OfferEMIEMIOffer {
	if o == nil {
		return OfferEMIEMIOffer{}
	}
	return o.Emi
}
