// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OfferWalletWalletOffer struct {
	Provider *string `json:"provider,omitempty"`
}

func (o *OfferWalletWalletOffer) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

type OfferWallet struct {
	App *OfferWalletWalletOffer `json:"app,omitempty"`
}

func (o *OfferWallet) GetApp() *OfferWalletWalletOffer {
	if o == nil {
		return nil
	}
	return o.App
}
